"use client";
import dynamic from "next/dynamic";
import {useEffect,useMemo,useState} from "react";
import {ArrowDownRight,ArrowUpRight,Minus,Plus,SunMedium,Zap} from "lucide-react";
const SolarScene=dynamic(()=>import("@/components/3d/SolarScene"),{ssr:false,loading:()=><div className="scene-fallback" aria-hidden/>});
const services=[["01","Strategy","Positioning, offer architecture and digital roadmaps built around how solar buyers actually decide."],["02","Web Design","High-trust experiences that make complex solar offers feel precise, credible and easy to act on."],["03","Development","Fast, accessible Next.js builds engineered for performance, scale and seamless integrations."],["04","SEO","Technical, local and service-area search systems designed to compound qualified visibility."],["05","Lead Generation","Calculators, funnels and conversion paths that turn interest into sales-ready opportunities."],["06","Growth","Analytics, experimentation and continuous optimization after the site goes live."]];
const projects=[{no:"01",name:"SunPeak Energy",type:"Residential Solar",goal:"Simplify the path from rooftop curiosity to a qualified consultation.",tech:"Strategy · UX · Next.js",theme:"sunpeak"},{no:"02",name:"VoltEra",type:"Solar + Battery",goal:"Position energy independence as a premium, intelligible product.",tech:"Brand system · 3D · Development",theme:"voltera"},{no:"03",name:"HelioGrid",type:"Commercial Solar",goal:"Turn complex commercial value into a decisive boardroom story.",tech:"UX · Data visualization · SEO",theme:"heliogrid"},{no:"04",name:"Northstar",type:"Regional Installer",goal:"Build a scalable service-area engine without losing local trust.",tech:"Content system · Local SEO · CRO",theme:"northstar"}];
const process=[["01","Discover","We learn the business, buyer, market and friction."],["02","Strategize","We define the message, system and measurement plan."],["03","Design","We turn strategy into an unmistakable digital experience."],["04","Build","We engineer it for speed, access and real-world use."],["05","Launch","We validate every path and release with confidence."],["06","Scale","We learn from behavior and improve what moves growth."]];
const faqs=[["How much does a SolarScale website cost?","Every engagement is scoped around the system you need—not a page count. After a focused discovery call, we provide a clear range, timeline and deliverables."],["Do you only work with solar companies?","Solar is our focus. That specialization lets us move faster on the language, buyer journey and conversion challenges unique to the industry."],["Can you redesign our existing website?","Yes. We can reposition, redesign and rebuild an existing site while preserving valuable search equity."],["Do you provide SEO?","Yes. Our work can include technical SEO, information architecture, local and service-area strategy and content systems."],["Can you build solar calculators?","Yes. We design savings, production, financing and qualification experiences around your inputs and sales process."],["Can you integrate our CRM?","Yes. We can connect forms and conversion journeys to the CRM, scheduling and automation tools your team uses."],["Can you work with companies outside the US?","Yes. The US is our primary market, but we work with ambitious solar businesses in other regions when the fit is right."],["How long does a project take?","Most complete website systems take roughly 8–14 weeks. Scope, integrations and content readiness affect the schedule."]];
export default function Home(){
 const[scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false),[activeService,setActiveService]=useState(0),[systemSize,setSystemSize]=useState(9.6);
 useEffect(()=>{const fn=()=>setScrolled(scrollY>40);fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"set_solar_system_size",title:"Set solar system size",description:"Update the visible energy model to a solar system size between 4 and 20 kW.",inputSchema:{type:"object",properties:{kilowatts:{type:"number",minimum:4,maximum:20}},required:["kilowatts"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=(input as {kilowatts?:unknown})?.kilowatts;if(typeof value!=="number"||!Number.isFinite(value)||value<4||value>20)throw new Error("kilowatts must be a number from 4 to 20");setSystemSize(value);return{kilowatts:value,annualProductionKwh:Math.round(value*1460)}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const energy=useMemo(()=>Math.round(systemSize*1460),[systemSize]),savings=useMemo(()=>Math.round(energy*.19),[energy]),co2=useMemo(()=>Math.round(energy*.00071),[energy]);
 return <main>
 <header className={scrolled?"site-nav scrolled":"site-nav"}><a className="wordmark" href="#top" aria-label="SolarScale home">SOLAR<span>SCALE</span></a><nav className={menu?"nav-links open":"nav-links"}>{["Work","Services","Process","Results","About"].map(x=><a key={x} onClick={()=>setMenu(false)} href={"#"+x.toLowerCase()}>{x}</a>)}</nav><a className="nav-cta magnetic" href="#contact">Start a project <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<Minus/>:<Plus/>}</button></header>
 <section className="hero" id="top"><div className="hero-grid" aria-hidden/><div className="hero-scene"><SolarScene/></div><div className="hero-content wrap"><p className="eyebrow">Digital growth for solar</p><h1><span>We build the</span><span>digital systems</span><span>that <em>scale</em> solar.</span></h1><div className="hero-bottom"><p>High-performance websites, search systems and digital experiences that turn solar attention into qualified opportunities.</p><div className="button-row"><a className="button button-accent" href="#work">See our work <ArrowDownRight size={19}/></a><a className="button button-ghost" href="#contact">Start a project</a></div></div></div><div className="hero-index">SOL / 001 <span>Scroll to explore</span></div></section>
 <div className="marquee"><div>{[0,1].map(i=><span key={i}>SOLAR <b>✦</b> DESIGN <b>✦</b> DEVELOPMENT <b>✦</b> SEO <b>✦</b> LEADS <b>✦</b> GROWTH <b>✦</b> CONVERSION <b>✦</b> </span>)}</div></div>
 <section className="intro light-section" id="about"><div className="wrap intro-layout"><p className="section-tag">01 / What we believe</p><div><h2>Solar companies don&apos;t need <span>another website.</span></h2><h2 className="engine-line">They need a digital engine.</h2><div className="intro-copy"><p>Your website should do more than look credible. It should sharpen your position, answer buyer questions, capture demand and give your team a system that improves over time.</p><p>SolarScale brings strategy, design, development, SEO, conversion and lead generation into one focused growth layer.</p></div></div></div></section>
 <section className="results light-section" id="results"><div className="wrap"><div className="section-head"><p className="section-tag">02 / Performance framework</p><p className="micro-note">Illustrative targets shown below.<br/>Replace with verified client data.</p></div><div className="stat-grid">{[["50+","Solar project capacity"],["3×","Conversion improvement goal"],["92%","Performance score target"],["24/7","Digital lead capture"]].map(([n,l])=><div className="stat" key={n}><strong>{n}</strong><span>{l}</span></div>)}</div></div></section>
 <section className="services dark-section" id="services"><div className="wrap service-layout"><div className="service-sticky"><p className="section-tag">03 / Capabilities</p><h2>Everything solar needs to <em>grow online.</em></h2><div className="service-orbit" aria-hidden><div><SunMedium/><span>{services[activeService][1]}</span></div></div></div><div className="service-list">{services.map((s,i)=><button className={activeService===i?"service active":"service"} key={s[0]} onMouseEnter={()=>setActiveService(i)} onFocus={()=>setActiveService(i)}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div><ArrowDownRight/></button>)}</div></div></section>
 <section className="solar-lab light-section"><div className="wrap"><div className="lab-heading"><p className="section-tag">04 / Solar intelligence</p><h2>We understand the system <span>behind the screen.</span></h2><p>A product experience can educate, qualify and convert—before a salesperson enters the conversation.</p></div><div className="dashboard"><div className="dash-top"><div><span>SolarScale / Energy model</span><strong>Residential outlook</strong></div><div className="live-label"><i/> Interactive concept</div></div><div className="dash-grid"><div className="production"><div className="production-label"><span>Annual production</span><Zap size={18}/></div><strong>{energy.toLocaleString()}</strong><small>kWh / year</small><div className="chart">{[42,58,70,84,94,100,97,89,76,61,47,38].map((h,i)=><i key={i} style={{height:String(h)+"%"}}/>)}</div><div className="months"><span>JAN</span><span>JUN</span><span>DEC</span></div></div><div className="dash-metrics"><div><span>Estimated savings</span><strong>{"$"+savings.toLocaleString()}</strong><small>/ year</small></div><div><span>CO₂ offset</span><strong>{co2}</strong><small>metric tons</small></div><div><span>Battery capacity</span><strong>13.5</strong><small>kWh</small></div></div></div><div className="system-control"><label htmlFor="system-size"><span>System size</span><strong>{systemSize.toFixed(1)} kW</strong></label><input id="system-size" type="range" min="4" max="20" step=".2" value={systemSize} onChange={e=>setSystemSize(+e.target.value)}/></div></div></div></section>
 <section className="work dark-section" id="work"><div className="wrap"><div className="work-head"><p className="section-tag">05 / Selected work</p><h2>Concepts built to move the industry <em>forward.</em></h2><p>Explorations of what category-leading solar experiences can become.</p></div><div className="project-list">{projects.map((p,i)=><article className="project" key={p.name}><div className={"project-visual "+p.theme}><div className="concept-label">SolarScale concept</div><div className="browser-ui"><div className="browser-nav"><b>{p.name.toUpperCase()}</b><span>ENERGY / MADE CLEAR</span></div><div className="browser-title">{i===0?"OWN YOUR POWER.":i===1?"STORE THE SUN.":i===2?"ENERGY AT SCALE.":"LOCAL POWER. BUILT HERE."}</div><div className="browser-sun"/><div className="browser-data"><span>EST. OUTPUT</span><strong>{[12840,16420,780000,14190][i].toLocaleString()} kWh</strong></div></div></div><div className="project-info"><span>{p.no}</span><div><p>{p.type}</p><h3>{p.name}</h3></div><p>{p.goal}</p><small>{p.tech}</small><ArrowUpRight/></div></article>)}</div></div></section>
 <section className="case-study light-section"><div className="wrap case-intro"><p className="section-tag">06 / Featured case study</p><div><span className="concept-pill">Concept project</span><h2>SunPeak Energy</h2><p>A conversion-first residential solar platform built around clarity, confidence and a shorter path to the right conversation.</p></div></div><div className="case-stage"><div className="case-desktop"><div className="mock-nav">SUNPEAK <span>Power your next chapter ↗</span></div><div className="mock-copy"><small>Residential energy, reimagined</small><strong>THE FUTURE<br/>LOOKS BRIGHT.</strong><p>Clean power. Clear numbers. Total control.</p></div><div className="mock-orb"/></div><div className="case-mobile"><div>SUNPEAK</div><strong>YOUR ROOF.<br/>YOUR POWER.</strong><div className="mobile-panel"><SunMedium/><span>Estimated annual production</span><b>12,840 kWh</b></div></div></div><div className="wrap case-notes">{[["Design decision","Replace industry clutter with one confident story and progressive disclosure."],["Conversion strategy","Lead with value, then earn the form through education and useful interaction."],["Outcome goal","Increase qualified consultation starts without inventing urgency or hiding complexity."]].map(x=><div key={x[0]}><span>{x[0]}</span><p>{x[1]}</p></div>)}</div></section>
 <section className="process dark-section" id="process"><div className="wrap"><div className="process-head"><p className="section-tag">07 / Process</p><h2>From first idea<br/>to measurable growth.</h2></div><div className="timeline">{process.map((p,i)=><div className="process-step" key={p[0]}><span>{p[0]}</span><div className="process-line"><i style={{width:String((i+1)/6*100)+"%"}}/></div><h3>{p[1]}</h3><p>{p[2]}</p></div>)}</div></div></section>
 <section className="difference light-section"><div className="wrap"><div className="difference-head"><p className="section-tag">08 / Why SolarScale</p><h2>Built differently.</h2><p>Specialization changes the work. We combine solar fluency with the standards of a premium digital product team.</p></div><div className="comparison"><div className="compare-label muted">Generic agency</div><div className="compare-label">SolarScale <span>✦</span></div>{[["Generic templates","Purpose-built experiences"],["A pretty website","A lead-generation system"],["Generic SEO","Solar-focused search strategy"],["Launch and leave","Measure and improve"]].map((r,i)=><div className="compare-row" key={i}><span>{r[0]}</span><ArrowUpRight/><strong>{r[1]}</strong></div>)}</div></div></section>
 <section className="testimonials light-section"><div className="wrap testimonial-grid"><p className="section-tag">09 / Client perspective</p><blockquote><span>“</span>Client testimonial goes here. Use this space for a specific, verifiable account of the partnership and the change it created.<footer>Placeholder testimonial <i>— Client name / Company role</i></footer></blockquote><p className="placeholder-note">Intentionally labeled placeholder. No fictional endorsement presented.</p></div></section>
 <section className="faq dark-section"><div className="wrap faq-layout"><div><p className="section-tag">10 / FAQ</p><h2>Clear answers.<br/><em>No pitch deck.</em></h2></div><div>{faqs.map((f,i)=><details key={f[0]}><summary><span>{String(i+1).padStart(2,"0")}</span>{f[0]}<Plus/></summary><p>{f[1]}</p></details>)}</div></div></section>
 <section className="final-cta" id="contact"><div className="energy-sun" aria-hidden><span/><span/><span/></div><div className="wrap cta-content"><p className="section-tag">A better digital future starts here</p><h2>Ready to <em>scale?</em></h2><p>Let&apos;s build the digital experience your solar company deserves.</p><a className="button button-dark magnetic" href="mailto:hello@solarscale.co">Start a project <ArrowUpRight/></a></div></section>
 <footer className="footer dark-section"><div className="wrap"><div className="footer-top"><div className="footer-mark">SOLAR<span>SCALE</span></div><p>Digital growth systems<br/>for solar companies.</p></div><div className="footer-links"><div><span>Navigate</span>{["Work","Services","Process","About","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()}>{x}</a>)}</div><div><span>Social</span><span className="social-pending">LinkedIn / Instagram<br/>Profiles added at launch</span></div><div><span>Contact</span><a href="mailto:hello@solarscale.co">hello@solarscale.co</a><a href="#contact">Start a project ↗</a></div></div><div className="footer-bottom"><span>© 2026 SolarScale</span><span>Built for the energy transition.</span><span>US / Worldwide</span></div></div></footer>
 </main>
}
