"use client";
import{Canvas,useFrame}from"@react-three/fiber";
import{useRef}from"react";
import*as THREE from"three";
function ArraySculpture(){
 const group=useRef<THREE.Group>(null),sun=useRef<THREE.Mesh>(null),node=useRef<THREE.Mesh>(null);
 useFrame((state)=>{if(!group.current)return;const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(!reduced){const time=state.clock.elapsedTime;group.current.rotation.y=THREE.MathUtils.lerp(group.current.rotation.y,-.42+Math.sin(time*.24)*.12+state.pointer.x*.08,.04);group.current.rotation.x=THREE.MathUtils.lerp(group.current.rotation.x,-.2+Math.sin(time*.3)*.035+state.pointer.y*.1,.04);group.current.rotation.z=THREE.MathUtils.lerp(group.current.rotation.z,.08+Math.sin(time*.4)*.025,.04);group.current.position.y=Math.sin(time*.7)*.08;if(sun.current){sun.current.position.x=2.5+Math.sin(time*.35)*.45;sun.current.position.y=1.8+Math.cos(time*.35)*.25}if(node.current)node.current.scale.setScalar(1+Math.sin(time*2.2)*.14)}});
 const cells=Array.from({length:24},(_,i)=>({x:(i%6-2.5)*.6,y:(Math.floor(i/6)-1.5)*.52,z:.04}));
 return <group ref={group} rotation={[-.2,-.42,.08]}><mesh position={[0,0,-.2]}><boxGeometry args={[4.25,2.65,.12]}/><meshStandardMaterial color="#0b1212" metalness={.98} roughness={.2}/></mesh><mesh position={[0,0,-.12]}><boxGeometry args={[4.02,2.42,.035]}/><meshStandardMaterial color="#183b3a" metalness={.65} roughness={.2}/></mesh>{cells.map((cell,index)=><mesh key={index} position={[cell.x,cell.y,cell.z]}><boxGeometry args={[.53,.45,.065]}/><meshPhysicalMaterial color={index%7===0?"#b7ff35":"#17413e"} metalness={.58} roughness={.14} clearcoat={1} emissive={index%7===0?"#6fa616":"#04100e"} emissiveIntensity={index%7===0?1.45:.3}/></mesh>)}<mesh position={[0,1.29,.04]}><boxGeometry args={[4.35,.07,.14]}/><meshStandardMaterial color="#b4c3b7" metalness={.95} roughness={.18}/></mesh><mesh position={[0,-1.29,.04]}><boxGeometry args={[4.35,.07,.14]}/><meshStandardMaterial color="#b4c3b7" metalness={.95} roughness={.18}/></mesh><mesh position={[-2.13,0,.04]}><boxGeometry args={[.07,2.65,.14]}/><meshStandardMaterial color="#b4c3b7" metalness={.95} roughness={.18}/></mesh><mesh position={[2.13,0,.04]}><boxGeometry args={[.07,2.65,.14]}/><meshStandardMaterial color="#b4c3b7" metalness={.95} roughness={.18}/></mesh><mesh position={[0,0,-.8]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.08,.08,1.8,20]}/><meshStandardMaterial color="#8fa499" metalness={.9} roughness={.25}/></mesh><mesh position={[0,-.03,-.55]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.045,.045,2.4,16]}/><meshStandardMaterial color="#8fa499" metalness={.9} roughness={.25}/></mesh><mesh ref={node} position={[0,0,.5]}><sphereGeometry args={[.11,24,24]}/><meshStandardMaterial color="#d8ff63" emissive="#a8ff22" emissiveIntensity={4}/></mesh><mesh ref={sun} position={[2.5,1.8,.2]}><sphereGeometry args={[.18,24,24]}/><meshBasicMaterial color="#dfff76"/></mesh></group>
}
export default function SolarScene(){return <Canvas dpr={[1,1.5]} camera={{position:[0,0,5.4],fov:42}} gl={{antialias:true,powerPreference:"high-performance",alpha:true}}><ambientLight intensity={.55}/><directionalLight position={[4,4,5]} intensity={3} color="#f7ffe0"/><pointLight position={[-3,-2,3]} intensity={18} color="#aaff2b" distance={7}/><pointLight position={[2,2,2]} intensity={8} color="#dfff76" distance={5}/><ArraySculpture/></Canvas>}
